/hik_camera:
  ros__parameters:
    camera_info_url: package://vision_bringup/config/camera_info.yaml
    camera_name: narrow_stereo
    exposure_time: 7500.0
    fps: 100.0
    gain: 16.0
    use_sensor_data_qos: true

